export const LOAD_POSTS = "App/Load/Posts"
export const SHOW_LOADER = "App/Loader/Show"
export const HIDE_LOADER = "App/Loader/Hide"
export const CREATE_USER = "App/Users/Create"
export const LOGIN_USER = "App/Users/Login"
export const USER_CHECK_STATE = "App/Users/Check"
export const SHOW_MESSAGE = "App/Message/Fire"
export const HIDE_MESSAGE = "App/Message/Hide"
export const LOAD_COMMENTS = "App/Comments/Load"

export const ACCESS_TOKEN = "d40622bf22188c88679eb1fa006b3e8ad2b38b3a4ba4286e0dc24c6c92da9243"
